# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_fio', models.CharField(max_length=200)),
                ('bid_email', models.CharField(max_length=200)),
                ('bid_about', models.TextField(verbose_name='Немного о себе')),
                ('bid_job', models.CharField(max_length=200)),
                ('bid_date', models.DateTimeField()),
                ('bid_from', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'bids',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_text', models.TextField()),
                ('event_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'events',
            },
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
