# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20170720_1932'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_photo',
            field=models.ImageField(blank=True, default='', upload_to='events/photos', verbose_name='фотография'),
        ),
    ]
