# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_event_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_photo',
            field=models.ImageField(blank=True, default='', upload_to='bids/photos', verbose_name='фотография'),
        ),
    ]
