# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20170721_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_photo',
            field=models.ImageField(blank=True, default='', upload_to='bids/photos', verbose_name='фотография'),
        ),
    ]
